- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

- name: Push Docker image to registry
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    push: yes
    source: local
